language: bash

script:
    # - bash <(curl -s -L https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/wss_agent.sh) -apiKey 63fbe101e3a045e592b9af5f5cef3ef98d6f0814534144f88221ed6b2fc82f7e -c whitesource-fs-agent.config -d ~/ -project TravisTest
    - bash curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/whitesource-fs-agent.jar
    - bash ls
    - ls
    - curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/whitesource-fs-agent.jar
    - bash ls
    - ls
    - bash curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/whitesource-fs-agent.config
    - curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/whitesource-fs-agent.config
    - bash echo "checkPolicies=ture" >  whitesource-fs-agent.config
    - bash java -jar whitesource-fs-agent.jar -apiKey 63fbe101e3a045e592b9af5f5cef3ef98d6f0814534144f88221ed6b2fc82f7e -c whitesource-fs-agent.config -d ~/ -project TravisTest
    