language: bash

script:
    # - bash <(curl -s -L https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/wss_agent.sh) -apiKey 63fbe101e3a045e592b9af5f5cef3ef98d6f0814534144f88221ed6b2fc82f7e -c whitesource-fs-agent.config -d ~/ -project TravisTest
    - curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/whitesource-fs-agent.jar
    - curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/whitesource-fs-agent.config
    - cat whitesource-fs-agent.config
    #- echo >> whitesource-fs-agent.config
    #- echo "checkPolicies=ture" >>  whitesource-fs-agent.config
    - cat whitesource-fs-agent.config
    #Create temporary file with new line in place
    - cat whitesource-fs-agent.config | sed -e "s/checkPolicies=false/checkPolicies=ture/" > temp_file.config
    #Copy the new file over the original file
    - mv temp_file.config whitesource-fs-agent.config
    - cat whitesource-fs-agent.config
    - echo "**********************************"
    - java -jar whitesource-fs-agent.jar -apiKey 63fbe101e3a045e592b9af5f5cef3ef98d6f0814534144f88221ed6b2fc82f7e -c whitesource-fs-agent.config -d ~/ -project TravisTest
    